# Generated by Django 3.2.8 on 2021-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elsys', '0006_auto_20211021_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='info',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='made',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
